site_description: "XLua"
github: https://github.com/Tencent/xLua
modify_github: https://github.com/Tencent/xLua/tree/master/docs/source/src/
copyright: © Copyright 2017 Tencent All Rights Reserved
copyright_desc: Tencent 2017